service: aws-serverless-eventbridge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - events:PutEvents
            - es:ESHttpPost
            - es:ESHttpPut
            - es:ESHttpHead
            - es:ESHttpDelete
          Resource: '*'
functions:
  indexdata:
    handler: IndexData.indexdata
    description: 'creat event from http'
    events: 
    - stream:
        type: dynamodb
        arn:
          Fn::GetAtt: [ DataTable, StreamArn ]
        startingPosition: LATEST
        bisectBatchOnFunctionError: true
        maximumRetryAttempts: 2
        parallelizationFactor: 1
        batchSize: 100
        destinations:
          onFailure:
            type: sqs
            arn:
              Fn::GetAtt: [ DLQueueDynamoDBStream, Arn ]
resources:
  - ${file(./resources/dynamodb/tables.yml)}
  - ${file(./resources/sqs/queues.yml)}